[Pleasured.noStruggle.Orgasm]
  # overrides female statement
  say = """
  The Thralls are stroking [mainName]'s shaft with dogged persistence, and the pleasure finally becomes to much to bear.  \
  He cums hard, his penis spurting its load on the ground between his knees"""


