[Pleasured.noStruggle.Orgasm]
  # overrides female statement
  say = """
  With one last cry of defeat, [mainName] gives in to the pleasure of the hands milking him down below.  \
  His penis begins to shoot spurts of cum\
  """


