[Pleasured.noStruggle.inju.gt3]
  say = ".  [HeShe]'s too exhausted to do anything but twitch and moan.  "

[Pleasured.noStruggle.inju.eq3]
  say = ".  Already exhausted and gasping for breath, [heShe] can't afford to waste the energy to fight it.  "
