[printCapturedLine]
  [printCapturedLine.Impregnation]
    NoMoralityInnocence = [
      "I... I must not let anyone know what's happened to me...",
      "If they find out, they'll all turn against me...",
      "It feels like... there's something really bad inside me..."
    ]
  [printCapturedLine.Hypnotized]
    LowInnocenceDignity = [
      "Cum, cum, cum...!",
       "Huh...  Why am I... touching myself...?  Well, whatever...",
       "I want to... dream some more..."
    ]
    NoInnocenceDignity = [
      "I'm tired... of resisting...",
      "Instead of thinking... let us just feel good...",
      "I wouldn't mind... continuing to dream..."
    ]
  [printCapturedLine.Drained]
    # No, Low 
    ConfidenceMorality = [
      "I don't care about anyone else, just let me die...",
      "I'm so tired... of fighting...",
      "I'm sorry, everyone... but I can't fight anymore...",

      "I hate giving them what they want, but if it lets me die...",
      "I'm... done...",
      "Even though I know that this energy will be used to hurt people... I can't help it...",

      "Fine, take my soul... I hope you choke on it...",
      "I was never strong after all...",
      "To think I was such a selfish person after all..."
    ]

